/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../app/app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './app.component.css.shim';
import * as import11 from '../../app/toolbar.component';
import * as import12 from './toolbar.component.ngfactory';
var renderType_SitesRunAppComponent_Host:import0.RenderComponentType = (null as any);
class _View_SitesRunAppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SitesRunAppComponent_0_4:import3.SitesRunAppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SitesRunAppComponent_Host0,renderType_SitesRunAppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('sites-run-app',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SitesRunAppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SitesRunAppComponent_0_4 = new import3.SitesRunAppComponent();
    this._appEl_0.initComponent(this._SitesRunAppComponent_0_4,[],compView_0);
    compView_0.create(this._SitesRunAppComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SitesRunAppComponent) && (0 === requestNodeIndex))) { return this._SitesRunAppComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._SitesRunAppComponent_0_4.ngAfterViewInit(); } }
  }
}
function viewFactory_SitesRunAppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SitesRunAppComponent_Host === (null as any))) { (renderType_SitesRunAppComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_SitesRunAppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SitesRunAppComponentNgFactory:import9.ComponentFactory<import3.SitesRunAppComponent> = new import9.ComponentFactory<import3.SitesRunAppComponent>('sites-run-app',viewFactory_SitesRunAppComponent_Host0,import3.SitesRunAppComponent);
const styles_SitesRunAppComponent:any[] = [import10.styles];
var renderType_SitesRunAppComponent:import0.RenderComponentType = (null as any);
class _View_SitesRunAppComponent0 extends import1.AppView<import3.SitesRunAppComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SitesRunToolbarComponent_0_4:import11.SitesRunToolbarComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SitesRunAppComponent0,renderType_SitesRunAppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'sites-run-toolbar',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import12.viewFactory_SitesRunToolbarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SitesRunToolbarComponent_0_4 = new import11.SitesRunToolbarComponent();
    this._appEl_0.initComponent(this._SitesRunToolbarComponent_0_4,[],compView_0);
    compView_0.create(this._SitesRunToolbarComponent_0_4,[],(null as any));
    this.init([],[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.SitesRunToolbarComponent) && (0 === requestNodeIndex))) { return this._SitesRunToolbarComponent_0_4; }
    return notFoundResult;
  }
}
export function viewFactory_SitesRunAppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SitesRunAppComponent> {
  if ((renderType_SitesRunAppComponent === (null as any))) { (renderType_SitesRunAppComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_SitesRunAppComponent,{})); }
  return new _View_SitesRunAppComponent0(viewUtils,parentInjector,declarationEl);
}